### ISSUE TITLE
Infection mode does not apply color on image shapes

### ISSUE THREAD

**Issue by knackstedt** [tsparticles/tsparticles#809]
**Describe the bug**
When infection mode is enabled, particles.shape.type = 'image', and images that have the replaceColor = true property, the infection stages do not apply color to the particles.

**To Reproduce**
1. Use SVG images and set 'replaceColor: true
2. Enable infections
3. Set particle type to image.
4. Observe no color change for infected particles.

**Expected behavior**
Particles with SVG and replaceColor should change color when infected.

**Screenshots**
Observation of no coloring on nodes:
![image](https://user-images.githubusercontent.com/29349167/92674460-57a6b180-f2eb-11ea-8e56-74a78f2a78c9.png)
Changing type to 'circle': 
![image](https://user-images.githubusercontent.com/29349167/92674594-ab18ff80-f2eb-11ea-9689-e9f4f5f98143.png)

**Desktop (please complete the following information):**
 - OS: Linux KDE Plasma X11, Windows 10
 - Browser Chrome, Firefox
 - Version
    - Chrome 84.x
    - Firefox 80.x
    - Edge 18.x

**Additional context**
Tested tsParticles versions: 1.17.0, 1.17.10, 1.18.0-alpha.14

[This](https://codepen.io/matteobruni/pen/dyoZbMb) Official CodePen suggests this is fault of upgrades in Chrome / FireFox.

Options Object:
```js
{
      fpsLimit: 60,
      infection: {
        enable: true,
        infections: 10,
        cure: true,
        stages: [
          {
            color: "#ff0000",
            duration: 10
          },
          {
            color: "#00ff00",
            duration: 10,
            rate: 0
          },
          {
            color: "#ffffff",
            duration: 1,
            rate: 0,
            infectedStage: 0
          }
        ]
      },
      particles: {
        number: {
          value: 70,
          density: {
            enable: true,
            value_area: 800
          }
        },
        color: {
          value: "#ffffff"
        },
        shape: {
          // type: "circle",
          type: 'image',
          image: [
            {
              src: "https://particles.matteobruni.it/images/sars-cov-2.png",
              // src: "/img/landingpage/desktop-gray_900.svg",
              replaceColor: true
            }

          ]
        },
        opacity: {
          value: 0.8,
          random: false,
          anim: {
            enable: false,
            speed: 3,
            opacity_min: 0.1,
            sync: false
          }
        },
        size: {
          value: 15,
          random: false,
          anim: {
            enable: false,
            speed: 20,
            size_min: 0.1,
            sync: false
          }
        },
        line_linked: {
          enable: false,
          distance: 150,
          color: "#ffffff",
          opacity: 0.4,
          width: 1
        },
        move: {
          collisions: true,
          enable: true,
          speed: 10,
          direction: "none",
          random: false,
          straight: false,
          out_mode: "bounce",
          attract: {
            enable: false,
            rotateX: 600,
            rotateY: 1200
          }
        }
      },
      interactivity: {
        detect_on: "canvas",
        events: {
          onhover: {
            enable: false,
            mode: "repulse"
          },
          onclick: {
            enable: false,
            mode: "push"
          },
          resize: true
        },
        modes: {
          grab: {
            distance: 400,
            line_linked: {
              opacity: 1
            }
          },
          bubble: {
            distance: 400,
            size: 40,
            duration: 2,
            opacity: 0.8,
            speed: 3
          },
          repulse: {
            distance: 200
          },
          push: {
            particles_nb: 4
          },
          remove: {
            particles_nb: 2
          }
        }
      },
      retina_detect: true
    }```

**Comment by matteobruni** [comment]
Hi @knackstedt,

Thanks for the report, I'll investigate it deeply for the next release

**Comment by matteobruni** [comment]
I've checked the issue, the color is replaced only when the particles is created, color animations are not working too.

At least I know what need to be fixed, I try to fix it for the 1.18 release.

**Comment by knackstedt** [comment]
@matteobruni 
Thanks my friend!

**Comment by tligier** [comment]
Can I have a go at this?

**Comment by matteobruni** [comment]
Hi @tligier,

Sure, it’s free at the moment

**Comment by Redseb** [comment]
Hi, I notice that the issue has been marked as done, is the fix available in the latest npm package? Thanks!

**Comment by matteobruni** [comment]
It’s not fixed since the infection plugin doesn’t support images, only colors

**Comment by Redseb** [comment]
I see, I'm running into the same issue but not using the infection plugin (can't change the color of svgs). For reference my config looks like the following: 
```js
<Particles
      id="tsparticles"
      options={{
        background: {
          color: {
            value: "#403d3c",
          },
          position: "50% 50%",
          repeat: "no-repeat",
          size: "cover",
        },
        fullScreen: {
          zIndex: -1,
        },
        particles: {
          move: {
            enable: true,
            outModes: {
              bottom: "out",
              left: "out",
              right: "out",
              top: "out",
            },
            direction: "bottom",
            angle: 20,
          },
          number: {
            density: {
              enable: true,
            },
            value: 30,
          },
          rotate: {
            random: {
              enable: true,
            },
            animation: {
              enable: true,
              speed: 5,
            },
            direction: "random",
          },
          color: {
            value: "#ffff00",
            animation: {
              enable: true,
              speed: -70,
              sync: true,
            },
          },
          shape: {
            image: {
              src: "icons/chart-line-solid.svg",
              width: 32,
              height: 32,
              // replaceColor: true,
            },
            type: "image",
          },
          size: {
            value: 32,
            animation: {
              speed: 1,
              minimumValue: 0.1,
            },
          },
          stroke: { color: "#ffffff", width: 1 },
        },
      }}
    />
```
Is changing the colors of svgs in general not supported or am I missing something here? Thanks again

**Comment by matteobruni** [comment]
The replace color is even more difficult because every color shade needs a new image to load, and this makes everything really bad in term of performance

**Comment by Redseb** [comment]
So changing svg colors through `replaceColor` is not supported? In that case, I will probably switch to  the `char` type instead of image and use the Font Awesome font.

**Comment by matteobruni** [comment]
> So changing svg colors through `replaceColor` is not supported? In that case, I will probably switch to the `char` type instead of image and use the Font Awesome font.

Exactly, images are good for performances when they are static since there's less to draw on the canvas, but every color change is an image to load and that loading is bad at runtime.

Using the font could be good, but try to see if the performances are still good since the text is a bit slower than the image
