### ISSUE TITLE
Particles not displaying on Safari / All Mobile Browsers

### ISSUE THREAD

**Issue by ghost** [tsparticles/tsparticles#946]
**Describe the bug**
Particles background on my end works and looks great locally via live-server and via the publish github page url while viewing the site on Edge/Chrome/Opera/Safari/Firefox. Ive sent the github link out to the client and a few mates for feedback and thats when I learned that the particle background doesn't seem to load on safari on any other computer except mine. Also, particle background does not load on any mobile browser. I went further and did more browser testing with browserstack and researched this issue and cannot come up with any solution to this bug. Any help is greatly and truly appreciated.

**To Reproduce**
1. Go to 'https://www.jasonguro.github.io/midas' on any web browser except Safari
2. Go to 'https://www.jasonguro.github.io/midas' on Safari
3. Compare the two browser windows (you'll that Safari is missing the particles in the background)
4. Send help this way.
View the github repo: 'https://github.com/jasonguro/midas'

**Expected behavior**
Particles should load and display in the background when viewing the link on Safari
 
**Screenshots**
![Messages Image(613168587)](https://user-images.githubusercontent.com/72325355/95552140-2d274180-09da-11eb-890e-49a916beb1de.jpeg)
The red and green in the background is the particles in the Chrome browser and they are missing in Safari

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.7
 - All Browsers (Doesn't work on safari for others, except browsing on my own machine)
 - Safari Version 14 (All my browsers are updated to the newest versions.) + I used BrowserStack

**Smartphone (please complete the following information):**
iPhone 11 Pro / iPhone 7 Plus
iOS 13.7
All Browsers (Doesn't work on any browsers, I tried Opera/Chrome/Safari/Edge/Firefox, all up-to-date versions.)

**Additional context**
I still haven't started making the site responsive, but doubt thats the issue for the mobile not displaying particles.

**On a sidenote:** If it's possible to make different images move in different directions, that would be awesome! For example in my site, the green arrows would move upwards and the red upside down arrows should move downwards.

**Comment by matteobruni** [comment]
Hi @jasonguro,

I checked your repo and you are using version `1.18.2`, can you try upgrading to `1.18.3`? That version should fix this bug.

About images direction yes it's possible. Check out this configuration: https://codepen.io/matteobruni/pen/MWymBxX

**Comment by ghost** [comment]
Updating the version did not fix the bug. As for the images direction thank you!

**Comment by ghost** [comment]
I assume by updating you meant updating the jsdeliver cdn link.

**Comment by matteobruni** [comment]
Yes, it's enough updating the CDN link.

I tried now your website on Safari, Chrome, Firefox, and Edge (Chromium version on Win10) but particles were working fine.

This is the URL I tried: <https://jasonguro.github.io/midas/> (with `www` I receive a security warning)

**Comment by ghost** [comment]
Super weird, im getting no particles on safari.

**Comment by matteobruni** [comment]
My main browser is Safari, it's more possible to not having them in other browsers (and it happened)

**Comment by ghost** [comment]
I see, i'm going to do more testing on other devices running safari and will get back to you.

**Comment by ghost** [comment]
Ok so I asked few more mates who are running safari 13.1, 13.1.2, 13.1.3 and its not working then i asked someone with 14.0 like myself and i'm assuming your running 14.0 also and its working great on 14. Older versions of Safari are having this issue I believe.

**Comment by matteobruni** [comment]
Thanks for the details, does safari 13.x have some console errors?

**Comment by ghost** [comment]
There are no console errors to report, i've checked on my multiple macbooks included an older mac and it wasn't working until I updated the mac osx which updated safari to 14 and from that point it started working.
